---
- name: Run Prometheus on K8s
  hosts: all

  tasks:

     - name: add Prometheus and Thanos repositories
       shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts& helm repo add bitnami https://charts.bitnami.com/bitnami & helm repo add stable "https://charts.helm.sh/stable" &  helm repo update

     - name: create namespace
       shell: kubectl create namespace monitoring
       ignore_errors: yes 
     
     - name: create secret
       shell: kubectl create secret generic thanos --from-file=object-store.yaml="{{ lookup('env','PWD') }}/object-store.yaml" -n monitoring
       ignore_errors: yes

     - name: deploy prometheus
       shell: helm install -f  "{{ lookup('env','PWD') }}/values.yaml" prometheus prometheus-community/kube-prometheus-stack -n monitoring

     - name: dploy thanos
       shell: helm install thanos bitnami/thanos -f "{{ lookup('env','PWD') }}/t-values.yaml" -n monitoring

