---
- name: Run Prometheus on K8s
  hosts: all

  tasks:

     - name: create namespace
       shell: kubectl create namespace monitoring 
     
     - name: create secret
       shell: kubectl create secret generic thanos --from-file=object-store.yaml="{{ lookup('env','PWD') }}/object-store.yaml" -n monitoring

     - name: deploy prometheus
       shell: helm install -f  "{{ lookup('env','PWD') }}/values.yaml" prometheus prometheus-community/kube-prometheus-stack -n monitoring

     - name: dploy thanos
       shell: helm install thanos bitnami/thanos -f "{{ lookup('env','PWD') }}/t-values.yaml" -n monitoring

